### ISSUE TITLE
Is this model working with text recognitionof vedic images

### ISSUE THREAD

**Issue by abhijeetshukla007** [Shreeshrii/tesstrain-Sanskrit-IAST#3]
Ex images 
1. https://images.indianexpress.com/2019/05/1_759-7.jpg
2. 2. https://www.bl.uk/britishlibrary/~/media/bl/global/dst%20discovering%20sacred%20texts/collection%20items/or-4481-f-17v.jpg?w=608&h=342&hash=091815CE168AA4832248382F6258186D. please response if its working

**Comment by Shreeshrii** [comment]
No. It won't work with manuscript scans.
